# Generated by Django 4.2.2 on 2023-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cardmolel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmolel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
